### ISSUE TITLE
Xcode 7 Issue

### ISSUE THREAD

**Issue by bullxu** [ServiceStack/ServiceStack.Swift#1]
The Xcode 7 ServiceStackXcode.dmg has 3 issues:

1) The generated DTO class extensions don't implement method of HasMetadata: public static var metadata (still HasReflect methods)
2) Xcode 7 gives error for the line of "typealias Return = XXX" for each Request class. Need to add public access modifier.
3) JsonServiceClient.swift includes ResponseStatus, ResponseError and ErrorResponse classes, which are also included in the auto-generated DTO file.

**Comment by mythz** [comment]
You need to upgrade the Server to v4.0.46 of ServiceStack, since it still has the `HasReflect` methods it means the server is using an older version of ServiceStack and you need to upgrade to v4.0.46 which is the first version to support Swift 2.0 / Xcode 7.

In future please provide the C# DTO's and generated Swift DTO models so we can identify the issue.

**Comment by bullxu** [comment]
Thanks this make much sense because when I use the http://techstacks.io, it comes with SwiftVersion 2.0 and Version 4.046 but my own SS API still was 4.044.

**Comment by mythz** [comment]
No worries, also be sure to check out the [v4.0.46 Release Notes for Xcode 7/ Swift 2.0 support](https://github.com/ServiceStack/ServiceStack/blob/master/docs/2015/release-notes.md#swift-20-support) which documents a few other changes required to support Swift 2.0.
